version: '3.5'
services:
  db:
    container_name: mysql
    image: mysql/mysql-server:8.0.30
    ports:
      - "4407:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
      - ./.volumes/mysql:/var/lib/mysql:rw
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1", ]
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Seoul"
