server:
  port: 8080
spring:
  datasource:
    write:
      hikari:
        jdbc-url: ${DB_RW_URL:jdbc:mysql://localhost:4407/sample}
        username: ${DB_RW_USERNAME:root}
        password: ${DB_RW_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 5
        pool-name: "read-write-pool"
        read-only: false
    read:
      hikari:
        jdbc-url: ${DB_RO_URL:jdbc:mysql://localhost:4408/sample}
        username: ${DB_RO_USERNAME:root}
        password: ${DB_RO_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 5
        pool-name: "read-only-pool"
        read-only: true
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    #org.springframework.transaction: DEBUG
    #org.springframework.transaction.interceptor: TRACE
