server:
  port: 8080
spring:
  datasource:
    read-write:
      hikari:
        jdbc-url: ${DB_RW_URL:jdbc:mysql://localhost:4407/sample}
        username: ${DB_RW_USERNAME:root}
        password: ${DB_RW_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 5
        pool-name: "read-write-pool"
        read-only: false
    read-only:
      hikari:
        jdbc-url: ${DB_RO_URL:jdbc:mysql://localhost:4407/sample}
        username: ${DB_RO_USERNAME:root}
        password: ${DB_RO_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 5
        pool-name: "read-only-pool"
        read-only: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    #org.springframework.transaction: DEBUG
    #org.springframework.transaction.interceptor: TRACE
